version: '3'
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports: 
      - 3000:3000
    volumes:
      - ./client/src:/client/src
    container_name: react-express-client-dev
    depends_on:
      - server
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3000
    volumes:
      - ./server/src:/server/src
    container_name: react-express-server-dev
